#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
#
# indentation is not needed but it makes it easier to read ;)
#
version = "1"

[global]
  initialize = true
  # prevent idle sleeping
  prevent-sleep = true

[default]
  repository = "rclone:b2:mack-timotheos"
  option = [
    "rclone.args=serve restic --stdio --b2-hard-delete --fast-list --verbose",
  ]
  password-file = "../sops-nix/secrets/users/timotheos/restic_b2_mack-timotheos"

  [default.backup]
    verbose = true
    source = ["/Users/timotheos"]
    exclude-file = "./exclude_home.txt"
    exclude-caches = true
    # SCHEDULING
    # run the backup on Mondays at 12:30 am
    schedule = "Mon *.*.* *:00,30"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = "mack-timotheos-b2backup_{{ .Now.DateOnly }}.log"
    schedule-lock-mode = "default"
    schedule-lock-wait = "5m"

  [default.retention]
    after-backup = true
    host = "mack"
    prune = true
    keep-last = 10
    keep-daily = 7
    keep-weekly = 12
    keep-monthly = 24
    keep-yearly = 25
