# yamllint disable-file
# .sops.yaml
keys:
  - &primary age1mhy95hjcr3l73fl39ufefmkdt6grqatw7pctjw0ntw7cr7tugslsl5k4tx
creation_rules:
  - path_regex: nix-darwin/secrets\.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: nix-darwin/secrets_home\.yaml$
    key_groups:
      - age:
          - *primary
stores:
  yaml:
    indent: 2
  json:
    indent: 2
  json_binary:
    indent: 2
